version: 2

models:
  - name: products
    description: Product history of each product and its price.
    columns:
      - name: id
        description: Primary key of the model
        tests:
          - dbt_utils.mutually_exclusive_ranges:
              lower_bound_column: price_created_at
              upper_bound_column: price_ended_at
              gaps: not_allowed